from urllib.parse import quote_plus
CATALOG=[
{"name":"Modern 3-Seater Sofa","category":"Sofa","platform":"IKEA","price":32999,"query":"modern 3 seater sofa"},{"name":"Minimalist Floor Lamp","category":"Lighting","platform":"Amazon","price":2499,"query":"minimalist floor lamp"},{"name":"Pendant Ceiling Light","category":"Lighting","platform":"IKEA","price":3999,"query":"pendant ceiling light"},{"name":"Wood Coffee Table","category":"Coffee Table","platform":"Flipkart","price":6999,"query":"wood coffee table"},{"name":"Ergonomic Study Chair","category":"Chair","platform":"Amazon","price":5499,"query":"ergonomic study chair"},{"name":"Queen Storage Bed","category":"Bed","platform":"IKEA","price":28999,"query":"queen storage bed"},{"name":"6-Seater Dining Table","category":"Dining Table","platform":"Flipkart","price":18999,"query":"6 seater dining table"},
{"name":"Vegetarian Catering Package","category":"Catering","platform":"Zomato","price":450,"query":"vegetarian catering"},{"name":"Party Catering Options","category":"Catering","platform":"Swiggy","price":500,"query":"party catering"},{"name":"Budget Event Venue","category":"Venue","platform":"OYO","price":12000,"query":"event venue"},{"name":"Birthday Decoration Kit","category":"Decoration","platform":"Amazon","price":1999,"query":"birthday decoration kit"},{"name":"Party Lighting Set","category":"Decoration","platform":"Flipkart","price":2999,"query":"party lighting"},
{"name":"Pearl Drop Earrings","category":"Earrings","platform":"Amazon","price":1799,"query":"pearl drop earrings"},{"name":"Minimal Gold-Tone Necklace","category":"Necklace","platform":"Flipkart","price":2499,"query":"gold tone necklace"},{"name":"Kundan Style Earrings","category":"Earrings","platform":"Amazon","price":3299,"query":"kundan earrings"},{"name":"Classic Bracelet","category":"Bracelet","platform":"Flipkart","price":1999,"query":"classic bracelet"}]
def platform_url(p,q):
    q=quote_plus(q); return {"Amazon":f"https://www.amazon.in/s?k={q}","Flipkart":f"https://www.flipkart.com/search?q={q}","IKEA":f"https://www.ikea.com/in/en/search/?q={q}","Swiggy":f"https://www.swiggy.com/search?query={q}","Zomato":f"https://www.zomato.com/search?query={q}","OYO":f"https://www.oyorooms.com/search?location={q}"}.get(p,f"https://www.google.com/search?q={q}")
def search_catalog(domain,budget,categories=None):
    cats={"home":{"Sofa","Lighting","Coffee Table","Chair","Bed","Dining Table"},"party":{"Catering","Venue","Decoration"},"jewelry":{"Earrings","Necklace","Bracelet"}}[domain]
    rows=[x for x in CATALOG if x["category"] in cats and x["price"]<=max(budget,1000)]
    if categories:
        wanted={x.lower() for x in categories}; pref=[x for x in rows if x["category"].lower() in wanted or any(w in x["name"].lower() for w in wanted)]; rows=pref or rows
    return [{**x,"estimated_price":x["price"],"url":platform_url(x["platform"],x["query"])} for x in rows]
